### ISSUE TITLE
FIX README BRO

### ISSUE THREAD

**Issue by daisied** [Z-8Bit/Qtile#1]
## Setting up 

1. Clone the repository with **`git clone https://github.com/Qtile.git`** and cd into it **`cd Qtile`**
2. Make the script an executable by doing **`chmod +x qtile-setup.sh`** 
3. Run the script by doing **`./qtile-setup.sh`**
4. Type the sudo password whenever asked.
5. Enjoy your new Qtile setup!

link is wrong, pls fix :pensive:

**Comment by Z-8Bit** [comment]
Oops, my bad.
